// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhowoluabckbbwrcihrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxob3dvbHVhYmNrYmJ3cmNpaHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NzAxODIsImV4cCI6MjA2MTA0NjE4Mn0.YTIXc6eLlaCm1h8zvFuKhdbggcCzVdRPs5POovmPtOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);